name = "NeighborJoining"
uuid = "3f465f53-8c2e-426b-b4f1-431dfde0fdf8"
authors = ["Benjamin Doran and collaborators"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
