name = "NeighborJoining"
uuid = "3f465f53-8c2e-426b-b4f1-431dfde0fdf8"
authors = ["Benjamin Doran and collaborators"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NewickTree = "b0a14db8-6308-4ebc-8917-f72cd81f5094"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NewickTree", "LinearAlgebra"]
